name: Run Unit Tests

# Run tests on pushes and PRs targeting develop
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy-qa:

    runs-on: [self-hosted, linux, X64, truex-old-qa, us-east-1]
    environment: qa

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn run test
